changelog:
  categories:
    - title: "New Features"
      labels:
        - "feat"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Others"
      labels:
        - "chore"
    - title: "All"
      labels:
        - "*"

  exclude:
    labels:
      - "test"
      - "docs"
      - "style"
      - "refactor"
