exclude: '\.ipynb$'
repos:
  - repo: git@github.com:abravalheri/validate-pyproject.git
    rev: v0.19
    hooks:
      - id: validate-pyproject

  - repo: git@github.com:igorshubovych/markdownlint-cli.git
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: [ -c, .markdownlint.yaml, --fix ]

  - repo: git@github.com:crate-ci/typos.git
    rev: typos-dict-v0.11.27
    hooks:
      - id: typos
        exclude: '\.csv$'

  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

