version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    pre_build:
      - npm install -g pnpm
      - |
        cd jupyter_frontend
        npm install -g pnpm
        pnpm install
        pnpm run build
      - pip install .
      - pip install -r docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
