version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    pre_build:
      - npm install -g pnpm
      - cd jupyter_frontend
      - pnpm install
      - pnpm build
      - cd ..
      - pip install .

sphinx:
  configuration: source/conf.py
