version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - ls `realpath ..`
      - ls `realpath .`
      #  安装项目代码：向上一级目录
      - pip install .
      #  安装文档依赖
      - pip install -r requirements.txt

sphinx:
  configuration: source/conf.py
