name: DevRelease

on:
  push:
    branches:
      - "main"
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'release:')"
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          # get tag history for version number
          fetch-depth: 0
          submodules: true
    - name: Get latest release from rs-linux-app
      id: get_release_from_rs-linux-app
      run: |
        response=$(curl -s -H "Authorization: token ${{ secrets.FETCH_RELEASE_FROM_RS_LINUX_APP }}" \
          "https://api.github.com/repos/cracknuts-team/rs-linux-app/releases")
        echo "Release data: $response"
        
        latest_release=$(echo "$response" | jq -r '.[] | select(.prerelease == false and .draft == false) | .tag_name' | sort -V | tail -n 1)

        asset_url=$(echo "$response" | jq -r --arg tag "$latest_release" '.[] | select(.tag_name == $tag) | .assets[] | select(.name | startswith("server-")) | .browser_download_url')
        asset_name=$(echo "$response" | jq -r --arg tag "$latest_release" '.[] | select(.tag_name == $tag) | .assets[] | select(.name | startswith("server-")) | .name')

        echo "Latest release tag: $latest_release"
        echo "Asset URL: $asset_url"
        echo "Asset Name: $asset_name"
        echo "::set-output name=asset_url::$asset_url"
        echo "::set-output name=asset_name::$asset_name"
    - name: Download latest asset from rs-linux-app
      run: |
        if [ -z "${{ steps.get_release_from_rs-linux-app.outputs.asset_url }}" ]; then
          echo "No asset found matching the criteria."
          exit 1
        fi
        mkdir -p $GITHUB_WORKSPACE/src/cracknuts/bin
        curl -L -H "Authorization: token ${{ secrets.FETCH_RELEASE_FROM_RS_LINUX_APP }}" \
        -o "$GITHUB_WORKSPACE/src/cracknuts/bin/${{ steps.get_release_from_rs-linux-app.outputs.asset_name }}" \
        "${{ steps.get_release_from_rs-linux-app.outputs.asset_url }}"
    - name: Update version.
      run: |
        incremented_version=`grep '__version__ = ' src/cracknuts/__init__.py | awk '{print $3}' | awk -F. '{printf "%d.%d.%d\n", $1, $2, $3+1}'`
        n_commits=`git rev-list $(git describe --tags --abbrev=0)..HEAD --count`
        if [ "$n_commits" -eq 0 ]; then
          echo "No new commits since the last tag. Terminating the action."
          exit 0
        fi
        dev_version="${incremented_version}.dev${n_commits}"
        sed -i "s/__version__ = \".*\"/__version__ = \"$dev_version\"/" src/cracknuts/__init__.py
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install node dependencies
      run: |
        cd jupyter_frontend
        npx pnpm install
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install build
        pip install twine
    - name: Build jupyter frontend
      run: |
        cd jupyter_frontend
        npm run clean-build
    - name: Build the project
      run: |
        python -m build
    - name: Upload to test pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TESTPYPI_TOKEN}}
      run: |
        python -m twine upload --repository testpypi dist/* --non-interactive
