name: PR-CI

on:
  pull_request:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ci dependencies
        run: |
          pipx install ruff
          pipx install typos
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Ruff check
        run: |
          ruff check
  spell:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Typos check
        run: |
          typos
