name: Release Build and Upload

on:
  push:
    tags:
      - 'v*'  # 每当推送类似 'v1.0.0' 的 tag 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Build the project
      run: |
        python -m build
        ls dist/  # 检查构建产物

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*  # 上传 dist 文件夹下的所有构建产物
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
